### ISSUE TITLE
quiz1 error

### ISSUE THREAD

**Issue by n-zu** [rust-lang/rustlings#1167]
The test expects 80, but it should be 40 right ?

> Mary is buying apples. One apple usually costs 2 Rustbucks, but if you buy *40 or more* at once, each apple only costs 1! Write a function that calculates the price of an order of apples given the quantity bought. No hints this time!

```
let price2 = calculate_price_of_apples(40);
```
```
assert_eq!(80, price2);
```

**Comment by ellmau** [comment]
I think so too - a friend who is just learning rust has been stumbling over this a couple of minutes ago.

**Comment by itami12354** [comment]
same goes with the third one which is

`let price3 = calculate_price_of_apples(65)`

and expects 130 when it should be 65 (cus yk 65>40)

**Comment by n-zu** [comment]
Its is fixed in  #1168

**Comment by itami12354** [comment]
Yea i checked right after commenting, probably should've done before, it's good it's been fixed i spent a few minutes trying to make sense of the question

**Comment by martinacantaro** [comment]
This is still not solved. #1168 needs to be merged in order to solve it
